name: as_flutter_blue_plus_web
version: 1.36.8-0
homepage: https://github.com/alekseisubbotin/flutter_blue_plus
publish_to: none

environment:
  sdk: ^3.3.0
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  as_flutter_blue_plus_platform_interface: 1.36.8-0
  flutter_web_plugins:
    sdk: flutter
  web: '>=0.5.0 <2.0.0'

flutter:
  plugin:
    implements: as_flutter_blue_plus
    platforms:
      web:
        pluginClass: AsFlutterBluePlusWeb
        fileName: as_flutter_blue_plus_web.dart
